[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
vapor = "HsdG697s3bvayLkKZgK1M3F34susRMjF3KphrFdd6qRH"

[programs.localnet]
vapor = "HsdG697s3bvayLkKZgK1M3F34susRMjF3KphrFdd6qRH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/saicharan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
